service: whereis # NOTE: update this with your service name

provider:
  name: aws
  runtime: python3.6
  region: eu-west-1

functions:
  whereis:
    handler: handler.whereis
    events:
      - http:
          method: post
          path: /prod
    vpc:
      securityGroupIds:
        - sg-***REMOVED***
      subnetIds:
        - subnet-***REMOVED***
        - subnet-***REMOVED***

plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: non-linux
